/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebServiceOrderTemplateTask {
    ServiceOrderTemplateTaskNumber?: number;
    StepNumber?: number;
    Subject?: string;
    Location?: string;
    TaskType?: string;
    TaskAction?: string;
    Priority?: string;
    TaskComment?: string;
    ResourceName?: string;
    Duration?: number;
    DurationIntervalType?: string;
    ScheduleAfterTask?: string;
    PreviousTaskoffset?: number;
    OffSetIntervalType?: string;
    RepType?: number;
    RepTypeDescription?: string;
    RepNumber?: number;
    RepName?: string;
    RepGroup?: string;
    StartTime?: Date;
}
