/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebContractMeterGroupBilling } from './tsiWebContractMeterGroupBilling';


export interface TsiWebContractMeterGroup {
    /**
     * Gets or sets the contract multiple meter group pricing key number
     */
    ContractMultipleMeterGroupPricingKeyNumber?: number;
    /**
     * Gets or sets the contract meter group
     */
    ContractMeterGroupKeyNumber?: number;
    /**
     * Gets or sets the contract meter group name
     */
    ContractMeterGroupName?: string;
    /**
     * Gets or sets the contract meter group billing style
     */
    BillingStyle?: string;
    /**
     * Gets or sets the StartDate
     */
    StartDate?: Date;
    /**
     * Gets or sets the EndDate
     */
    EndDate?: Date;
    /**
     * Gets or sets the FlatRate
     */
    FlatRate?: number;
    /**
     * Gets or sets the ItemID
     */
    ItemID?: string;
    /**
     * Gets or sets the LastBilledUsage
     */
    LastBilledUsage?: number;
    /**
     * Gets or sets the LastBilledDate
     */
    LastBilledDate?: Date;
    /**
     * Gets or sets the NextBillingDate
     */
    NextBillingDate?: Date;
    /**
     * Gets or sets the TotalUsageBilled
     */
    TotalUsageBilled?: number;
    LockPricing?: boolean;
    PriceLockingEndDate?: Date;
    UsePriceEscalation?: boolean;
    EscalationPercent?: number;
    EscalationPeriod?: number;
    NextPriceEscalationDate?: Date;
    BasePrice?: number;
    /**
     * Gets or sets the ContractMeterGroupBillings
     */
    ContractMeterGroupBillings?: Array<TsiWebContractMeterGroupBilling>;
}
