/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebAccountAsset {
    itemID?: string;
    itemDescription?: string;
    serialNumber?: string;
    status?: string;
    statusComment?: string;
    quantity?: number;
    vendorInvoiceNumber?: string;
    purchasedFromUs?: boolean;
    datePurchased?: Date;
    purchasePrice?: number;
    warrantyExpiration?: Date;
    lastPMDate?: Date;
    currMeterReading?: number;
    origMeterReading?: number;
    nextPMDate?: Date;
    servicePriority?: number;
    contractNumber?: number;
    contractDetailNumber?: number;
    location?: string;
    contactName?: string;
    contactNumber?: number;
    contactPhone?: string;
    yearlyMaintPrice?: number;
    datePurchasedFromVendor?: Date;
    manufacturerWarrantyExpiration?: Date;
    reference?: string;
    statusDate?: Date;
    transferTo?: number;
    transferDate?: Date;
    allowExchange?: boolean;
    exchangeNumber?: number;
    itemExchangedFor?: number;
    assemblyFlag?: boolean;
    comments?: string;
    creditMemoNumber?: number;
    creditMemoDetailNumber?: number;
    creditMemoAssemblyDetailNumber?: number;
    creditMemoQuantity?: number;
    invoiceNumber?: number;
    invoiceDetailNumber?: number;
    invoiceAssemblyDetailNumber?: number;
    manufacturerPartNumber?: string;
    vendorAccountNumber?: number;
    bMFLastProcessed?: Date;
    ipAddress?: string;
    nextActionDate?: Date;
    nextActionType?: string;
    nextActionTriggersWorkflow?: boolean;
    replacedByItemId?: string;
    warrantyExpirationTriggersWorkflow?: boolean;
    primaryRepNumber?: number;
    printOnCustomerFacingReports?: boolean;
    deviceId?: string;
}
