/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebQuoteDetailAssemblyItem } from './tsiWebQuoteDetailAssemblyItem';


export interface TsiWebQuoteDetailItem {
    QuoteDetailItemNumber?: number;
    PriceLevelDescription?: string;
    Assembly?: Array<TsiWebQuoteDetailAssemblyItem>;
    LineNumber?: number;
    PriceLevel?: number;
    VendorAccountNumber?: number;
    OriginalQuoteNumber?: number;
    ServiceOrderDetailNumber?: number;
    SubtotalIndent?: number;
    AssociatedFooterLineNumber?: number;
    AssociatedHeaderLineNumber?: number;
    SubtotalFooterItemNumber?: number;
    SubtotalHeaderItemNumber?: number;
    ProjectPhaseNumber?: number;
    InvoiceDetailNumber?: number;
    ItemId?: string;
    ItemDescription?: string;
    UnitOfMeasure?: string;
    InstallLocation?: string;
    ApplyDiscountOff?: string;
    PriceAdjuster?: string;
    NonStockItemType?: string;
    NonStockVendorItemNumber?: string;
    Type?: string;
    AssemblyType?: string;
    Taxable?: boolean;
    IsAssembly?: boolean;
    GSTExempt?: boolean;
    IsCommentOnly?: boolean;
    IsStockItem?: boolean;
    PrintOnQuote?: boolean;
    UseBookPricesAndDiscounts?: boolean;
    SubjectToProviderTax?: boolean;
    ItemCanBeDiscounted?: boolean;
    UseThisCostWhenOrdering?: boolean;
    PrintOnInvoice?: boolean;
    SubjectToSingleItemTax?: boolean;
    PrintSubTotalHeaderFooter?: boolean;
    OrderByDate?: Date;
    Quantity?: number;
    QuantityFilled?: number;
    QuantityBackOrdered?: number;
    QuantityPosted?: number;
    UnitHoursNeeded?: number;
    TotalHoursNeeded?: number;
    QuantityOrdered?: number;
    QuantityReceived?: number;
    QuantityAssignedToServiceOrders?: number;
    DiscountPercent?: number;
    AdjustmentPercent?: number;
    HoursEntered?: number;
    TaxableAmount?: number;
    ManufacturerListPrice?: number;
    BookPrice?: number;
    SellingPrice?: number;
    TotalSellingPrice?: number;
    Cost?: number;
    TotalCost?: number;
    GSTaxableAmount?: number;
    ActualUnitCost?: number;
    DiscountAmount?: number;
    ProviderTaxableAmount?: number;
    AdjustmentAmount?: number;
    TotalDiscount?: number;
    IsSerialized?: boolean;
}
