/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SystemNullableTsiWebOptionalDateTime } from './systemNullableTsiWebOptionalDateTime';


export interface TsiWebQuoteAssemblyDetailAdjustment {
    itemId?: string;
    quantity?: number;
    adjustedSellingPrice?: number;
    estimatedCost?: number;
    orderByDate?: SystemNullableTsiWebOptionalDateTime;
    useThisCostWhenOrdering?: boolean;
    printOnInvoice?: boolean;
    printOnQuote?: boolean;
}
