/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebAgreementBillTo } from './tsiWebAgreementBillTo';


export interface TsiWebAgreement {
    /**
     * Gets or sets the AccountNumber
     */
    AccountNumber?: number;
    /**
     * Gets or sets the External Product
     */
    ExternalProduct?: string;
    /**
     * Gets or sets the Start date
     */
    StartDate?: Date;
    /**
     * Gets or sets the End Date
     */
    EndDate?: Date;
    /**
     * Gets or sets the Type of agreement
     */
    Type?: string;
    /**
     * Gets or sets the sales tax codes of the agreement
     */
    SalesTaxCode?: string;
    /**
     * Gets or sets the Contact number
     */
    ContractNumber?: number;
    /**
     * Gets or sets the Last Billed Date
     */
    LastBilledDate?: Date;
    /**
     * Gets or sets the Last Polled Date
     */
    LastPolledDate?: Date;
    /**
     * Gets or sets the InvoiceComments
     */
    InvoiceComments?: string;
    /**
     * Gets or sets the InvoiceDetailFormat
     */
    InvoiceDetailFormat?: boolean;
    /**
     * Gets or sets the MakeAllItemsTaxExempt
     */
    MakeAllItemsTaxExempt?: boolean;
    /**
     * Gets or sets the ConsolidatedInvoice
     */
    ConsolidatedInvoice?: boolean;
    /**
     * Gets or sets the EmailInvoiceFlag
     */
    EmailInvoiceFlag?: boolean;
    /**
     * Gets or sets the AutomatedBilling
     */
    AutomatedBilling?: boolean;
    /**
     * Gets or sets the BillingPeriod
     */
    BillingPeriod?: number;
    /**
     * Gets or sets the BillingPeriodDescription
     */
    BillingPeriodDescription?: string;
    /**
     * Gets or sets the NextBillingPeriod
     */
    NextBillingPeriod?: Date;
    /**
     * Gets or sets the DayToBill
     */
    DayToBill?: number;
    /**
     * Gets or sets the DayToProcessPayment
     */
    DayToProcessPayment?: number;
    /**
     * Gets or sets the PayMethod
     */
    PayMethod?: number;
    /**
     * Gets or sets the PayMethodName
     */
    PayMethodName?: string;
    /**
     * Gets or sets the MonthlyTotal
     */
    MonthlyTotal?: boolean;
    /**
     * Gets or sets the FkPayMethods
     */
    BilledPeriodTotal?: boolean;
    /**
     * Gets or sets the SummarizedInvoiceFormat
     */
    SummarizedInvoiceFormat?: boolean;
    /**
     * Gets or sets the FkPayMethods
     */
    DetailedInvoiceFormat?: boolean;
    /**
     * Gets or sets the TotalPrice
     */
    TotalPrice?: number;
    /**
     * Gets or sets the TotalCost
     */
    TotalCost?: number;
    /**
     * Gets or sets the DateCreated
     */
    DateCreated?: Date;
    /**
     * Gets or sets the AgreementBillTo
     */
    AgreementBillTo?: TsiWebAgreementBillTo;
}
