/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebTask } from './tsiWebTask';


export interface TsiWebTaskSummary {
    TaskNumber?: number;
    Task?: TsiWebTask;
    AccountName?: string;
    PhoneNumber?: string;
    FaxNumber?: string;
    ContactName?: string;
    ContactEmailAddress?: string;
    ContactPhoneNumber?: string;
    ScheduledForRepName?: string;
    ScheduledByRepName?: string;
    ProjectName?: string;
    ProjectPhase?: string;
    ProjectSubPhase?: string;
    ServiceOrderDescription?: string;
    QuoteDescription?: string;
    OpportunityName?: string;
}
