/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebUpdateExpenseModel {
    expenseTypeNumber?: number;
    expenseType?: string;
    repNumber?: number;
    expensePaymentTypeNumber?: number;
    expensePaymentType?: string;
    expenseDateTime?: Date;
    expenseAmount?: number;
    odometerStart?: number;
    odometerEnd?: number;
    distance?: number;
    comments?: string;
    billable?: boolean;
    reimbursable?: boolean;
    distanceType?: string;
    acceptanceStatus?: string;
    rejectedReason?: string;
}
