/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebAlternateAddress } from './tsiWebAlternateAddress';
import { TsiWebPerson } from './tsiWebPerson';


export interface TsiWebVendor {
    VendorAccountNumber?: number;
    VendorAccountName?: string;
    OurCustomerNumber?: string;
    PhoneNumber?: string;
    InternetID?: string;
    MinimumOrderQuantity?: number;
    MinimumOrderAmount?: number;
    CreditLimit?: number;
    DiscountPercent?: number;
    DiscountDays?: number;
    NetDays?: number;
    FreightTerms?: string;
    ShippingMethods?: string;
    StandingRMANumber?: string;
    RMAShipToAddressNumber?: number;
    PurchaseOrderLeadTime?: string;
    APVendorID?: string;
    Address?: TsiWebAlternateAddress;
    URL1?: string;
    URL1Description?: string;
    URL2?: string;
    URL2Description?: string;
    PrimaryContact?: TsiWebPerson;
}
