/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebAddress } from './tsiWebAddress';
import { TsiWebRepPreferences } from './tsiWebRepPreferences';


export interface TsiWebRepDetail {
    repNumber?: number;
    personalAccountNumber?: number;
    address?: TsiWebAddress;
    homePhone?: string;
    mobilePhone?: string;
    status?: string;
    inactive?: boolean;
    repPreferences?: TsiWebRepPreferences;
    firstName?: string;
    lastName?: string;
    phoneNumber?: string;
    emailAddress?: string;
    title?: string;
    displayName?: string;
    searchName?: string;
}
