/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebAssemblyDetail } from './tsiWebAssemblyDetail';
import { TsiWebPriceBookItem } from './tsiWebPriceBookItem';


export interface TsiWebPriceBookItemSummary {
    itemId?: string;
    priceBookItemNumber?: number;
    item?: TsiWebPriceBookItem;
    assembly?: Array<TsiWebAssemblyDetail>;
    defaultProjectPhase?: string;
    vendorPartNumbers?: string;
    /**
     * Gets or sets QuantityOnHand of the item in the pricebook.
     */
    quantityOnHand?: number;
    /**
     * Gets or sets QuantityReserved of the item in the pricebook.
     */
    quantityReserved?: number;
    /**
     * Gets or sets QuantityOnOrder of the item in the pricebook.
     */
    quantityOnOrder?: number;
    /**
     * Gets or sets Available Quantity of the item in the pricebook.
     */
    available?: number;
}
