/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SystemNullableTsiWebOptionalDateTime } from './systemNullableTsiWebOptionalDateTime';


export interface TsiWebCreateServiceOrderPartsUsedModel {
    LineNumber?: number;
    ItemId?: string;
    PriceBookItemNumber?: number;
    ItemDescription?: string;
    UseBookPricesAndDiscounts?: boolean;
    AllowPriceLessThanCost?: boolean;
    Taxable?: boolean;
    SubjectToProviderTax?: boolean;
    PrintOnInvoice?: boolean;
    UnderContract?: boolean;
    ItemCanBeDiscounted?: boolean;
    EstimatedCost?: number;
    UseThisCostWhenOrdering?: boolean;
    CostGLCode?: string;
    IncomeGLCode?: string;
    PriceLevel?: number;
    SellingPrice?: number;
    Quantity?: number;
    ServiceOrderItemsServicedNumber?: number;
    Memo?: string;
    OrderByDate?: SystemNullableTsiWebOptionalDateTime;
    ProjectPhaseNumber?: number;
    InstallLocation?: string;
}
