/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebDocument } from './tsiWebDocument';


export interface TsiWebDocumentSummary {
    documentId?: number;
    accountNumber?: number;
    accountName?: string;
    contactNumber?: number;
    contactName?: string;
    appliesToDocumentType?: string;
    appliesToDocumentNumber?: number;
    document?: TsiWebDocument;
}
