/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebServiceOrderExpense {
    ExpenseNumber?: number;
    ExpenseAmount?: number;
    RepNumber?: number;
    RepName?: string;
    Comments?: string;
    Billable?: boolean;
    OdometerStart?: number;
    OdometerEnd?: number;
    Distance?: number;
    ExpenseTypeNumber?: number;
    ExpenseTypeDescription?: string;
    AcceptanceStatus?: string;
    RejectedReason?: string;
    ReviewedBy?: number;
    ReviewedByName?: string;
    Reimbursable?: boolean;
    ExpenseDateTime?: Date;
    ExpensePaymentTypeNumber?: number;
    DateCreated?: Date;
    ExpensePaymentDescription?: string;
}
