/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SystemNullableTsiWebSplitDateTime } from './systemNullableTsiWebSplitDateTime';
import { TsiWebConversionItem } from './tsiWebConversionItem';


export interface TsiWebAddQuoteToNewServiceOrderModel {
    quoteToSOType: string;
    projectNumber?: number;
    contractNumber?: number;
    briefDescription?: string;
    dateTimeRequested?: SystemNullableTsiWebSplitDateTime;
    newServiceOrderPhaseNumber?: number;
    type?: string;
    status?: string;
    technicianAssigned?: number;
    itemsToConvert?: Array<TsiWebConversionItem>;
    projectPhaseNumber?: number;
    allowInactiveContract?: boolean;
    allowFutureContract?: boolean;
    allowContractNoRemaining?: boolean;
}
