/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebBasis } from './tsiWebBasis';
import { TsiWebContractBillToAddress } from './tsiWebContractBillToAddress';


export interface TsiWebContract {
    /**
     * Gets or sets the contract description
     */
    Description?: string;
    /**
     * Gets or sets the contract type
     */
    ContractType?: string;
    /**
     * Gets or sets the contract reference
     */
    Reference?: string;
    /**
     * Gets or sets the contract DateWritten
     */
    DateWritten?: Date;
    /**
     * Gets or sets the contract created by
     */
    CreatedBy?: number;
    /**
     * Gets or sets the contract status
     */
    Status?: string;
    IsActive?: boolean;
    ContractRemaining?: string;
    IsFutureContract?: boolean;
    HasContractRemaining?: boolean;
    /**
     * Gets or sets the contract payment type
     */
    PaymentType?: string;
    /**
     * Gets or sets the contract CustomerPONumber
     */
    CustomerPONumber?: string;
    /**
     * Gets or sets the contract contact name
     */
    ContactName?: string;
    /**
     * Gets or sets the contract DefaultSOPriority
     */
    DefaultServiceOrderPriority?: string;
    /**
     * Gets or sets the contract AssignedTech
     */
    AssignedTech?: number;
    /**
     * Gets or sets the contract start date
     */
    StartDate?: Date;
    /**
     * Gets or sets the contract EndDate
     */
    EndDate?: Date;
    /**
     * Gets or sets the contract DaysLeft
     */
    DaysLeft?: number;
    /**
     * Gets or sets the contract LinkedAgreement
     */
    LinkedAgreement?: number;
    /**
     * Gets or sets the contract LimitServiceOrdersToItemsCovered
     */
    LimitServiceOrdersToItemsCovered?: boolean;
    /**
     * Gets or sets the contract Price
     */
    Price?: number;
    /**
     * Gets or sets the PricingMethod
     */
    PricingMethod?: string;
    /**
     * Gets or sets the BilledToDateAmount
     */
    BilledToDateAmount?: number;
    /**
     * Gets or sets the RepToCredit
     */
    RepToCredit?: number;
    /**
     * Gets or sets the RenewContractNumber
     */
    RenewContractNumber?: number;
    /**
     * Gets or sets the SalesTaxCode
     */
    SalesTaxCode?: string;
    /**
     * Gets or sets the BillDayOfMonth
     */
    BillDayOfMonth?: number;
    /**
     * Gets or sets the BillStartMonth
     */
    BillStartMonth?: number;
    /**
     * Gets or sets the AutoInvoice
     */
    AutoInvoice?: boolean;
    /**
     * Gets or sets the DaysAheadToInvoice
     */
    DaysAheadToInvoice?: number;
    /**
     * Gets or sets the EmailInvoice
     */
    EmailInvoice?: boolean;
    /**
     * Gets or sets the AllowInvoiceConsolidation
     */
    AllowInvoiceConsolidation?: boolean;
    /**
     * Gets or sets the PrintIncludesMemo
     */
    PrintIncludesMemo?: boolean;
    /**
     * Gets or sets the PrintSpecialInstructions
     */
    PrintSpecialInstructions?: boolean;
    /**
     * Gets or sets the InvoiceTerms
     */
    InvoiceTerms?: string;
    /**
     * Gets or sets the AutoPay
     */
    AutoPay?: boolean;
    /**
     * Gets or sets the DayOfMonthToPay
     */
    DayOfMonthToPay?: number;
    /**
     * Gets or sets the PayMethod
     */
    PayMethod?: number;
    /**
     * Gets or sets the PayMethodName
     */
    PayMethodName?: string;
    /**
     * Gets or sets the BillingCycle
     */
    BillingCycle?: string;
    /**
     * Gets or sets the BillingCycle Description
     */
    BillingCycleDescription?: string;
    /**
     * Gets or sets the BillingStyle
     */
    BillingStyle?: string;
    /**
     * Gets or sets the GLIncomeCode
     */
    GLIncomeCode?: string;
    /**
     * Gets or sets the PriceBillingText
     */
    PriceBillingText?: string;
    /**
     * Gets or sets the LastDayOfPeriod
     */
    LastDayOfPeriod?: number;
    /**
     * Gets or sets the BaseUsageItemID
     */
    BaseUsageItemID?: string;
    /**
     * Gets or sets the BaseUsageDescription
     */
    BaseUsageDescription?: string;
    /**
     * Gets or sets the OverageItemID
     */
    OverageItemID?: string;
    /**
     * Gets or sets the OverageDescription
     */
    OverageDescription?: string;
    OverageRate?: number;
    OveragePriceLevel?: number;
    /**
     * Gets or sets the include comments
     */
    Includes?: string;
    /**
     * Gets or sets the SpecialInstructions
     */
    SpecialInstructions?: string;
    /**
     * Gets or sets the RenewalNotes
     */
    RenewalNotes?: string;
    /**
     * Gets or sets the GeneralNotes
     */
    GeneralNotes?: string;
    /**
     * Gets or sets the Tripsincluded (MaxVisits)
     */
    TripsIncluded?: number;
    /**
     * Gets or sets the trips remaining (callsLeft)
     */
    TripsRemaining?: number;
    /**
     * Gets or sets the additional trip charge (PerCallPrice)
     */
    AdditionalTripCharge?: number;
    /**
     * Gets or sets the response hours (ResponseTime)
     */
    ResponseHours?: number;
    /**
     * Gets or sets the Basis
     */
    BasisType?: string;
    /**
     * Gets or sets the Basis
     */
    Basis?: TsiWebBasis;
    /**
     * Gets or sets the Billto
     */
    BillTo?: TsiWebContractBillToAddress;
    /**
     * Gets or sets the contract TemplateID
     */
    TemplateID?: string;
    /**
     * Gets or sets the Duration period of a template
     */
    DurationPeriod?: string;
    /**
     * Gets or sets the Duration quantity of a template
     */
    DurationQuantity?: number;
    /**
     * Gets or sets the LastBillingDate
     */
    LastBillingDate?: Date;
    BilledThruDate?: Date;
    BasePrice?: number;
    UseBasePrice?: boolean;
    VendorContract?: string;
    CreditUtilizationTime?: boolean;
    UtilizeOverride?: boolean;
    UseLaborOverride?: boolean;
    BillingOverride?: boolean;
    Billable?: boolean;
    Chargeable?: boolean;
    UseDailyProration?: boolean;
    TimeLogRateDiscount?: number;
    FixedHourlyRate?: number;
    LaborBillingType?: string;
    LaborBillingTypeDescription?: string;
    BasisTypeDescription?: string;
    BillingOption?: string;
    DefaultLogReason?: string;
    BillToAccountNumber?: number;
    BillToAddressType?: string;
    AlternateBillToAddressID?: number;
}
