/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SystemNullableTsiWebOptionalDateTime } from './systemNullableTsiWebOptionalDateTime';
import { TsiWebAlternateAddress } from './tsiWebAlternateAddress';


export interface TsiWebUpdateQuoteModel {
    ContactNumber?: number;
    RepNumber?: number;
    OpportunityNumber?: number;
    ProjectNumber?: number;
    ProjectPhaseNumber?: number;
    ApprovedByRepNumber?: number;
    LeaseMonths?: number;
    PayMethodId?: number;
    Description?: string;
    AlternateContactPhoneNumber?: string;
    Comment?: string;
    Job?: string;
    Type?: string;
    Terms?: string;
    Source?: string;
    Status?: string;
    SignedBy?: string;
    ShippingInstruction?: string;
    PackingInstruction?: string;
    Shipper?: string;
    ShippingMethod?: string;
    InternalComment?: string;
    TotalLineComment?: string;
    CustomerPurchaseOrder?: string;
    SalesTaxCode?: string;
    PaymentMethod?: string;
    BillingComment?: string;
    TrackingNumber?: string;
    LeaseBuyOut?: string;
    ExpirationDate?: SystemNullableTsiWebOptionalDateTime;
    StatusDate?: SystemNullableTsiWebOptionalDateTime;
    SignedDate?: SystemNullableTsiWebOptionalDateTime;
    ApprovedDate?: SystemNullableTsiWebOptionalDateTime;
    ShipDate?: SystemNullableTsiWebOptionalDateTime;
    DisplayOnPortal?: boolean;
    PrintLeaseInfo?: boolean;
    Freight?: number;
    TradeIn?: number;
    Deposit?: number;
    LeaseDown?: number;
    LeaseRate?: number;
    ApplyQuoteProjectPhaseToDetailItems?: boolean;
    DiscountType?: string;
    DiscountAmount?: number;
    DiscountMarginPercent?: number;
    DiscountSellForPrice?: number;
    DiscountPercent?: number;
    CanDiscountedItemsGetQuoteDiscount?: boolean;
    ShipToAddressType?: string;
    ShipToAddressAccountNumber?: number;
    ShipTo?: TsiWebAlternateAddress;
    AlternateShipToAddressID?: number;
    BillToAddressType?: string;
    BillToAddressAccountNumber?: number;
    BillTo?: TsiWebAlternateAddress;
    AlternateBillToAddressID?: number;
    UseAlternateShipToTaxCode?: boolean;
}
