/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebServiceOrderTemplatePart } from './tsiWebServiceOrderTemplatePart';
import { TsiWebServiceOrderTemplateTask } from './tsiWebServiceOrderTemplateTask';
import { TsiWebServiceOrderTemplateTimeLog } from './tsiWebServiceOrderTemplateTimeLog';


export interface TsiWebServiceOrderTemplate {
    templateId?: number;
    templateName?: string;
    briefDescription?: string;
    dispatchBoardNumber?: number;
    technicianAssigned?: number;
    technicianAssignedName?: string;
    associatedTechsGroup?: string;
    status?: string;
    serviceOrderType?: string;
    priority?: string;
    estimatedHours?: number;
    estimatedMinutes?: number;
    workRequested?: string;
    workPerformed?: string;
    internalComments?: string;
    useDefaultContract?: boolean;
    contactProfile?: string;
    useContractPriority?: boolean;
    templateTasks?: Array<TsiWebServiceOrderTemplateTask>;
    templateParts?: Array<TsiWebServiceOrderTemplatePart>;
    templateTimeLogs?: Array<TsiWebServiceOrderTemplateTimeLog>;
}
