/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebQuote } from './tsiWebQuote';


export interface TsiWebQuoteSummary {
    quoteNumber?: number;
    quote?: TsiWebQuote;
    details?: number;
    serviceOrdersCreatedFromQuote?: number;
    purchaseOrdersContainingQuoteItems?: number;
    accountName?: string;
    phoneNumber?: string;
    faxNumber?: string;
    contactName?: string;
    contactEmailAddress?: string;
    contactPhoneNumber?: string;
    ownerName?: string;
    ownerEmailAddress?: string;
    ownerPhoneNumber?: string;
    lastEditedRepName?: string;
    approvedRepName?: string;
    payMethodName?: string;
    priceLevelDescription?: string;
    specialInstructions?: string;
    creditHoldInstructions?: string;
    opportunityName?: string;
    projectDescription?: string;
    projectPhase?: string;
    hasProjectBeenInvoiced?: boolean;
    isLocked?: boolean;
    changeOrderDescription?: string;
    changeOrderDateCreated?: Date;
}
