/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebBasis } from './tsiWebBasis';
import { TsiWebContractBillToAddress } from './tsiWebContractBillToAddress';


export interface TsiWebContract {
    /**
     * Gets or sets the contract description
     */
    description?: string;
    /**
     * Gets or sets the contract type
     */
    contractType?: string;
    /**
     * Gets or sets the contract reference
     */
    reference?: string;
    /**
     * Gets or sets the contract DateWritten
     */
    dateWritten?: Date;
    /**
     * Gets or sets the contract created by
     */
    createdBy?: number;
    /**
     * Gets or sets the contract status
     */
    status?: string;
    isActive?: boolean;
    contractRemaining?: string;
    isFutureContract?: boolean;
    hasContractRemaining?: boolean;
    /**
     * Gets or sets the contract payment type
     */
    paymentType?: string;
    /**
     * Gets or sets the contract CustomerPONumber
     */
    customerPONumber?: string;
    /**
     * Gets or sets the contract contact name
     */
    contactName?: string;
    /**
     * Gets or sets the contract DefaultSOPriority
     */
    defaultServiceOrderPriority?: string;
    /**
     * Gets or sets the contract AssignedTech
     */
    assignedTech?: number;
    /**
     * Gets or sets the contract start date
     */
    startDate?: Date;
    /**
     * Gets or sets the contract EndDate
     */
    endDate?: Date;
    /**
     * Gets or sets the contract DaysLeft
     */
    daysLeft?: number;
    /**
     * Gets or sets the contract LinkedAgreement
     */
    linkedAgreement?: number;
    /**
     * Gets or sets the contract LimitServiceOrdersToItemsCovered
     */
    limitServiceOrdersToItemsCovered?: boolean;
    /**
     * Gets or sets the contract Price
     */
    price?: number;
    /**
     * Gets or sets the PricingMethod
     */
    pricingMethod?: string;
    /**
     * Gets or sets the BilledToDateAmount
     */
    billedToDateAmount?: number;
    /**
     * Gets or sets the RepToCredit
     */
    repToCredit?: number;
    /**
     * Gets or sets the RenewContractNumber
     */
    renewContractNumber?: number;
    /**
     * Gets or sets the SalesTaxCode
     */
    salesTaxCode?: string;
    /**
     * Gets or sets the BillDayOfMonth
     */
    billDayOfMonth?: number;
    /**
     * Gets or sets the BillStartMonth
     */
    billStartMonth?: number;
    /**
     * Gets or sets the AutoInvoice
     */
    autoInvoice?: boolean;
    /**
     * Gets or sets the DaysAheadToInvoice
     */
    daysAheadToInvoice?: number;
    /**
     * Gets or sets the EmailInvoice
     */
    emailInvoice?: boolean;
    /**
     * Gets or sets the AllowInvoiceConsolidation
     */
    allowInvoiceConsolidation?: boolean;
    /**
     * Gets or sets the PrintIncludesMemo
     */
    printIncludesMemo?: boolean;
    /**
     * Gets or sets the PrintSpecialInstructions
     */
    printSpecialInstructions?: boolean;
    /**
     * Gets or sets the InvoiceTerms
     */
    invoiceTerms?: string;
    /**
     * Gets or sets the AutoPay
     */
    autoPay?: boolean;
    /**
     * Gets or sets the DayOfMonthToPay
     */
    dayOfMonthToPay?: number;
    /**
     * Gets or sets the PayMethod
     */
    payMethod?: number;
    /**
     * Gets or sets the PayMethodName
     */
    payMethodName?: string;
    /**
     * Gets or sets the BillingCycle
     */
    billingCycle?: string;
    /**
     * Gets or sets the BillingCycle Description
     */
    billingCycleDescription?: string;
    /**
     * Gets or sets the BillingStyle
     */
    billingStyle?: string;
    /**
     * Gets or sets the GLIncomeCode
     */
    gLIncomeCode?: string;
    /**
     * Gets or sets the PriceBillingText
     */
    priceBillingText?: string;
    /**
     * Gets or sets the LastDayOfPeriod
     */
    lastDayOfPeriod?: number;
    /**
     * Gets or sets the BaseUsageItemID
     */
    baseUsageItemID?: string;
    /**
     * Gets or sets the BaseUsageDescription
     */
    baseUsageDescription?: string;
    /**
     * Gets or sets the OverageItemID
     */
    overageItemID?: string;
    /**
     * Gets or sets the OverageDescription
     */
    overageDescription?: string;
    overageRate?: number;
    overagePriceLevel?: number;
    /**
     * Gets or sets the include comments
     */
    includes?: string;
    /**
     * Gets or sets the SpecialInstructions
     */
    specialInstructions?: string;
    /**
     * Gets or sets the RenewalNotes
     */
    renewalNotes?: string;
    /**
     * Gets or sets the GeneralNotes
     */
    generalNotes?: string;
    /**
     * Gets or sets the Tripsincluded (MaxVisits)
     */
    tripsIncluded?: number;
    /**
     * Gets or sets the trips remaining (callsLeft)
     */
    tripsRemaining?: number;
    /**
     * Gets or sets the additional trip charge (PerCallPrice)
     */
    additionalTripCharge?: number;
    /**
     * Gets or sets the response hours (ResponseTime)
     */
    responseHours?: number;
    /**
     * Gets or sets the Basis
     */
    basisType?: string;
    /**
     * Gets or sets the Basis
     */
    basis?: TsiWebBasis;
    /**
     * Gets or sets the Billto
     */
    billTo?: TsiWebContractBillToAddress;
    /**
     * Gets or sets the contract TemplateID
     */
    templateID?: string;
    /**
     * Gets or sets the Duration period of a template
     */
    durationPeriod?: string;
    /**
     * Gets or sets the Duration quantity of a template
     */
    durationQuantity?: number;
    /**
     * Gets or sets the LastBillingDate
     */
    lastBillingDate?: Date;
    billedThruDate?: Date;
    basePrice?: number;
    useBasePrice?: boolean;
    vendorContract?: string;
    creditUtilizationTime?: boolean;
    utilizeOverride?: boolean;
    useLaborOverride?: boolean;
    billingOverride?: boolean;
    billable?: boolean;
    chargeable?: boolean;
    useDailyProration?: boolean;
    timeLogRateDiscount?: number;
    fixedHourlyRate?: number;
    laborBillingType?: string;
    laborBillingTypeDescription?: string;
    basisTypeDescription?: string;
    billingOption?: string;
    defaultLogReason?: string;
    billToAccountNumber?: number;
    billToAddressType?: string;
    alternateBillToAddressID?: number;
}
