/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebContact } from './tsiWebContact';


export interface TsiWebContactSummary {
    ContactNumber?: number;
    Contact?: TsiWebContact;
    PhoneNumber?: string;
    EmailAddress?: string;
    FaxNumber?: string;
    SearchName?: string;
    AccountName?: string;
    IsPrimaryContact?: boolean;
    JournalEntries?: number;
    OpenOpportunities?: number;
    OpenServiceOrders?: number;
    PastDueTasks?: number;
}
