/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebContract } from './tsiWebContract';
import { TsiWebContractAccount } from './tsiWebContractAccount';
import { TsiWebCustomField } from './tsiWebCustomField';
import { TsiWebItemCovered } from './tsiWebItemCovered';
import { TsiWebPerson } from './tsiWebPerson';


export interface TsiWebContractDetail {
    /**
     * Gets or sets the ContractNumber
     */
    contractNumber?: number;
    /**
     * Gets or sets the ContractAccount
     */
    contractAccount?: Array<TsiWebContractAccount>;
    /**
     * Gets or sets the Contract
     */
    contract?: TsiWebContract;
    /**
     * Gets or sets Created by rep
     */
    createdByRep?: TsiWebPerson;
    /**
     * Gets or sets assigned tech
     */
    assignedTechRep?: TsiWebPerson;
    /**
     * Gets or sets the rep to credit
     */
    repToCredit?: TsiWebPerson;
    /**
     * Gets or sets the ItemsCovered
     */
    itemsCovered?: Array<TsiWebItemCovered>;
    /**
     * Gets or sets the CustomFields
     */
    customFields?: Array<TsiWebCustomField>;
}
