/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SystemNullableTsiWebOptionalDateTime } from './systemNullableTsiWebOptionalDateTime';


export interface TsiWebUpdateServiceOrderItemServicedModel {
    Quantity?: number;
    MeterReading?: number;
    ClicksUsed?: number;
    ItemID?: string;
    ItemDescription?: string;
    Location?: string;
    Problem?: string;
    Repair?: string;
    SerialNumber?: string;
    WarrantyCovered?: boolean;
    UpdateContractMetersType?: string;
    CompleteDate?: SystemNullableTsiWebOptionalDateTime;
    LastPreventativeMaintenanceDate?: SystemNullableTsiWebOptionalDateTime;
    NextPreventativeMaintenanceDate?: SystemNullableTsiWebOptionalDateTime;
    Symptom1?: string;
    Symptom2?: string;
    Symptom3?: string;
    Symptom4?: string;
    Symptom5?: string;
    Resolution1?: string;
    Resolution2?: string;
    Resolution3?: string;
    Resolution4?: string;
    Resolution5?: string;
    AddItemToCustomerAssets?: boolean;
    IncludeAssemblyDetailsWhenAddedToCustomerAssets?: boolean;
    AllowDecreasedMeterReadings?: boolean;
}
