/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebAccount } from './tsiWebAccount';
import { TsiWebCustomField } from './tsiWebCustomField';
import { TsiWebPerson } from './tsiWebPerson';
import { TsiWebTask } from './tsiWebTask';
import { TsiWebTaskChecklistItem } from './tsiWebTaskChecklistItem';


export interface TsiWebTaskDetail {
    TaskNumber?: number;
    Task?: TsiWebTask;
    Account?: TsiWebAccount;
    Contact?: TsiWebPerson;
    ScheduledForRep?: TsiWebPerson;
    ScheduledByRep?: TsiWebPerson;
    ProjectName?: string;
    ProjectPhase?: string;
    ProjectSubPhase?: string;
    ServiceOrderDescription?: string;
    QuoteDescription?: string;
    OpportunityName?: string;
    TaskChecklist?: Array<TsiWebTaskChecklistItem>;
    CustomFields?: Array<TsiWebCustomField>;
}
