/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebQuoteAssemblyDetailAdjustment } from './tsiWebQuoteAssemblyDetailAdjustment';


export interface TsiWebCreateQuoteDetailItemModel {
    LineNumber?: number;
    ProjectPhaseNumber?: number;
    PriceBookItemNumber?: number;
    ItemId?: string;
    ItemDescription?: string;
    PriceLevel?: number;
    InstallLocation?: string;
    PriceAdjuster?: string;
    OrderByDate?: Date;
    Taxable?: boolean;
    SubjectToProviderTax?: boolean;
    PrintOnInvoice?: boolean;
    PrintOnQuote?: boolean;
    ItemCanBeDiscounted?: boolean;
    UseThisCostWhenOrdering?: boolean;
    UseBookPricesAndDiscounts?: boolean;
    CalculateUsingAdjustedDiscountPercent?: boolean;
    AllowPriceLessThanCost?: boolean;
    CanAdjustToMaxDiscount?: boolean;
    AdjustedSellingPrice?: number;
    EstimatedCost?: number;
    AdjustedDiscountPercent?: number;
    Quantity?: number;
    OpenAssemblyAdjustments?: Array<TsiWebQuoteAssemblyDetailAdjustment>;
}
