/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebOpportunity {
    name: string;
    type?: string;
    status: string;
    source?: string;
    notes: string;
    nextStep: string;
    competition: string;
    closeReason?: string;
    strategy?: string;
    howDidYouHearAboutUs?: string;
    stageId?: number;
    probabilityPercent?: number;
    owner?: number;
    accountNumber?: number;
    contactNumber?: number;
    age?: number;
    lastModifiedByRepNumber?: number;
    estimatedCloseDate?: Date;
    closeDate?: Date;
    nextDate?: Date;
    lastStageChangeDate?: Date;
    createdDate?: Date;
    lastModifiedDate?: Date;
    expectedAmount?: number;
    bestCaseAmount?: number;
    worstCaseAmount?: number;
    finalQuoteAmount?: number;
}
