/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebSubContractor {
    AccountNumber?: number;
    Name?: string;
    Address1?: string;
    Address2?: string;
    City?: string;
    State?: string;
    PostalCode?: string;
    Country?: string;
    PhoneNumber?: string;
    PrimaryContactName?: string;
    PrimaryContactEmailAddress?: string;
    PrimaryContactPhoneNumber?: string;
    Status?: string;
}
