/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebAlternateAddress } from './tsiWebAlternateAddress';
import { TsiWebPerson } from './tsiWebPerson';


export interface TsiWebVendor {
    vendorAccountNumber?: number;
    vendorAccountName?: string;
    ourCustomerNumber?: string;
    phoneNumber?: string;
    internetID?: string;
    minimumOrderQuantity?: number;
    minimumOrderAmount?: number;
    creditLimit?: number;
    discountPercent?: number;
    discountDays?: number;
    netDays?: number;
    freightTerms?: string;
    shippingMethods?: string;
    standingRMANumber?: string;
    rMAShipToAddressNumber?: number;
    purchaseOrderLeadTime?: string;
    aPVendorID?: string;
    address?: TsiWebAlternateAddress;
    uRL1?: string;
    uRL1Description?: string;
    uRL2?: string;
    uRL2Description?: string;
    primaryContact?: TsiWebPerson;
}
