/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebUpdateTaskModel {
    scheduleConflictedTask?: boolean;
    canUpdateOtherRepTask?: boolean;
    comment?: string;
    accountNumber?: number;
    contactNumber?: number;
    scheduledForRepNumber?: number;
    scheduledByRepNumber?: number;
    serviceOrderNumber?: number;
    serviceOrderTemplateNumber?: number;
    quoteNumber?: number;
    opportunityNumber?: number;
    projectNumber?: number;
    projectPhaseNumber?: number;
    projectSubPhaseAssignmentNumber?: number;
    startDate?: Date;
    startTime?: Date;
    endDate?: Date;
    endTime?: Date;
    action?: string;
    type?: string;
    dateScheduled?: Date;
    priorityNumber?: number;
    priority?: string;
    hasAlarm?: boolean;
    alarmDateTime?: Date;
    alarmReminderQuantity?: number;
    alarmReminderInterval?: string;
    isCompleted?: boolean;
    isPrivate?: boolean;
    resourceName?: string;
    isGlobalTask?: boolean;
    isAppointment?: boolean;
    subject?: string;
    location?: string;
    dueDate?: Date;
    dueTime?: Date;
}
