/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebPriceBookItem {
    /**
     * Gets or sets PartNumber of the item in the pricebook.
     */
    PartNumber?: string;
    /**
     * Gets or sets the item description in the pricebook.
     */
    ItemDescription: string;
    /**
     * Gets or sets the Type.
     */
    Type?: string;
    /**
     * Gets or sets the item status.
     */
    Status: string;
    /**
     * Gets or sets Created Date of the item in the pricebook.
     */
    DateCreated?: Date;
    /**
     * Gets or sets LastEditDate of the item in the pricebook.
     */
    LastEditDate?: Date;
    /**
     * Gets or sets LastSoldDate of the item in the pricebook.
     */
    LastSoldDate?: Date;
    /**
     * Gets or sets ManufacturerListPrice of the item in the pricebook.
     */
    ManufacturerListPrice?: number;
    /**
     * Gets or sets the description in the pricebook.
     */
    Description2?: string;
    /**
     * Gets or sets the description in the pricebook.
     */
    Description3?: string;
    /**
     * Gets or sets the ItemCategory.
     */
    ItemCategory?: string;
    /**
     * Gets or sets the ItemSubCategory.
     */
    ItemSubCategory?: string;
    /**
     * Gets or sets the item Comments.
     */
    Comments: string;
    ItemCanBeDiscounted?: boolean;
    Features?: string;
    ManufacturerName?: string;
    ManufacturerPartNumber?: string;
    UnitOfMeasure?: string;
    Weight?: string;
    UPC?: string;
    WarrantyDays?: string;
    IVRPartNumber?: number;
    LaborHoursRequired?: number;
    Bin?: string;
    ItemURL?: string;
    PictureFile?: string;
    Serialized?: boolean;
    Inactive?: boolean;
    HotItem?: boolean;
    Taxable?: boolean;
    SubjectToSingleItemTax?: boolean;
    SubjectToProviderTax?: boolean;
    GSTExempt?: boolean;
    UseAssemblyGLCodes?: boolean;
    PrintOnInvoice?: boolean;
    PrintOnQuote?: boolean;
    AddToCustomerInventory?: boolean;
    AddOnlyAssemblyDetailtoCustomerInventory?: boolean;
    ReceivingGLCode?: string;
    MaintenancePrice?: number;
    MaintenancePercentage?: number;
    BaseCost?: number;
    RepairCost?: number;
    AverageCost?: number;
    ExchangeValue?: number;
    AccountingLinkSalesCode?: string;
    DiscountTier?: number;
    ApplyQuantityDiscountsToAssemblyDetail?: boolean;
    AssemblyType?: string;
    PrimaryVendorAccountNumber?: number;
    ProviderTaxTypeNumber?: number;
    DefaultProjectPhaseNumber?: number;
}
