/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SystemNullableTsiWebOptionalDateTime } from './systemNullableTsiWebOptionalDateTime';
import { TsiWebQuoteAssemblyDetailAdjustment } from './tsiWebQuoteAssemblyDetailAdjustment';


export interface TsiWebQuoteDetailItemModel {
    priceLevel?: number;
    projectPhaseNumber?: number;
    installLocation?: string;
    priceAdjuster?: string;
    itemDescription?: string;
    orderByDate?: SystemNullableTsiWebOptionalDateTime;
    taxable?: boolean;
    subjectToProviderTax?: boolean;
    printOnQuote?: boolean;
    printOnInvoice?: boolean;
    itemCanBeDiscounted?: boolean;
    useThisCostWhenOrdering?: boolean;
    useBookPricesAndDiscounts?: boolean;
    calculateUsingAdjustedDiscountPercent?: boolean;
    allowPriceLessThanCost?: boolean;
    canAdjustToMaxDiscount?: boolean;
    adjustedSellingPrice?: number;
    estimatedCost?: number;
    quantity?: number;
    adjustedDiscountPercent?: number;
    openAssemblyAdjustments?: Array<TsiWebQuoteAssemblyDetailAdjustment>;
}
