/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebAlternateAddress } from './tsiWebAlternateAddress';


export interface TsiWebCreateQuoteModel {
    AccountNumber: number;
    ExistingQuoteNumber?: number;
    ContactNumber?: number;
    OpportunityNumber?: number;
    ProjectNumber?: number;
    ProjectPhaseNumber?: number;
    RepNumber?: number;
    ShipToAddressAccountNumber?: number;
    BillToAddressAccountNumber?: number;
    AlternateShipToAddressID?: number;
    AlternateBillToAddressID?: number;
    ShipToAddressType?: string;
    ShipTo?: TsiWebAlternateAddress;
    BillToAddressType?: string;
    BillTo?: TsiWebAlternateAddress;
    Description?: string;
    UseAlternateShipToTaxCode?: boolean;
    UpdateDetailsToReflectCurrentPricing?: boolean;
    PreserveLineItemPercentageDiscounts?: boolean;
    ApplyQuoteProjectPhaseToDetailItems?: boolean;
    AddMissingDetailProjectPhasesToProject?: boolean;
}
