/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebTimeEntryReason {
    logReason?: string;
    chargable?: boolean;
    standardRate?: number;
    itemID?: string;
    logType?: string;
    unitFactor?: number;
    billable?: boolean;
    laborItemID?: string;
    billingUnit?: string;
    IVRID?: number;
    roundingToNearestMinutes?: number;
    minimumMinutes?: number;
    laborRateCategoryNumber?: number;
    laborRateCategoryDescription?: string;
    overtimeIndicator?: boolean;
    premiumTimeIndicator?: boolean;
    doNotCopyToWorkPerformed?: boolean;
    rGBColor?: number;
    creditUtilizationTime?: boolean;
    appliesTo?: string;
}
