/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebAccountAssetAssemblyDetail {
    AccountAssetAssemblyDetailNumber?: number;
    ItemID?: string;
    ItemDescription?: string;
    SerialNumber?: string;
    Quantity?: number;
    PurchasedFromUs?: boolean;
    DatePurchased?: Date;
    PurchasePrice?: number;
    WarrantyExpiration?: Date;
    ManufacturerWarrantyExpiration?: Date;
    VendorInvoiceNumber?: string;
    Status?: string;
    StatusComment?: string;
    StatusDate?: Date;
    TransferTo?: number;
    TransferDate?: Date;
    CreditMemoQuantity?: number;
    AllowExchange?: boolean;
    ItemExchangedFor?: number;
    ExchangeNumber?: number;
    InvoiceNumber?: number;
    InvoiceDetailNumber?: number;
    InvoiceAssemblyDetailNumber?: number;
    CreditMemoNumber?: number;
    CreditMemoDetailNumber?: number;
    CreditMemoAssemblyDetailNumber?: number;
    ManufacturerPartNumber?: string;
    VendorAccountNumber?: number;
    PurchasedFromVendorDate?: Date;
    NextActionDate?: Date;
    NextActionType?: string;
    NextActionTriggersWorkflow?: boolean;
    ReplacedByItemId?: string;
    WarrantyExpirationTriggersWorkflow?: boolean;
    PrintOnCustomerFacingReports?: boolean;
}
