/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebAccountManagedAsset {
    /**
     * Gets or sets AssetId
     */
    managedAssetNumber?: number;
    /**
     * Gets or sets the account number
     */
    accountNumber?: number;
    /**
     * Gets or sets Provider
     */
    provider?: string;
    /**
     * Gets or sets AssetType
     */
    assetType?: string;
    /**
     * Gets or sets ProviderAssetName
     */
    providerAssetName?: string;
    /**
     * Gets or sets ProviderAssetId
     */
    providerAssetId?: string;
    /**
     * Gets or sets the Price
     */
    price?: number;
    /**
     * Gets or sets the PriceLevel
     */
    priceLevel?: number;
    /**
     * Gets or sets the PriceLevelDescription
     */
    priceLevelDescription?: string;
    /**
     * Gets or sets the ExternalId
     */
    externalId?: string;
    /**
     * Gets or sets the DateAdded
     */
    dateAdded?: Date;
    /**
     * Gets or sets the DeviceURL
     */
    deviceURL?: string;
    /**
     * Gets or sets the LastPolledDate
     */
    lastPolledDate?: Date;
    /**
     * Gets or sets the DateRemoved
     */
    dateRemoved?: Date;
    /**
     * Gets or sets the IPAdress
     */
    iPAddress?: string;
    /**
     * Gets or sets the MacAddress
     */
    mACAddress?: string;
    /**
     * Gets or sets the OS
     */
    OS?: string;
    /**
     * Gets or sets the SerialNumber
     */
    serialNumber?: string;
    /**
     * Gets or sets the Description
     */
    description?: string;
    /**
     * Gets or sets the last ogged-in user
     */
    lastLoggedInUser?: string;
    /**
     * Gets or sets the CPU
     */
    CPU?: string;
    /**
     * Gets or sets the Memory
     */
    memory?: string;
    /**
     * Gets or sets the Hard drive space
     */
    hardDriveSpace?: string;
    /**
     * Gets or sets UseFlatPrice
     */
    useFlatPrice?: boolean;
}
