/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebTaskLibrary {
    taskLibraryKeyNumber?: number;
    subject?: string;
    location?: string;
    taskType?: string;
    taskAction?: string;
    priorityNumber?: number;
    priorityText?: string;
    taskComment?: string;
    resourceName?: string;
    duration?: number;
    durationInterval?: string;
}
