/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebAccountAsset } from './tsiWebAccountAsset';
import { TsiWebAccountAssetAssemblyDetail } from './tsiWebAccountAssetAssemblyDetail';


export interface TsiWebAccountAssetSummary {
    AccountAssetNumber?: number;
    AccountNumber?: number;
    Asset?: TsiWebAccountAsset;
    Assembly?: Array<TsiWebAccountAssetAssemblyDetail>;
    WarrantyCovered?: boolean;
}
