/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebAlternateAddress } from './tsiWebAlternateAddress';


export interface TsiWebQuote {
    accountNumber: number;
    contactNumber?: number;
    repNumber: number;
    lastEditedByRepNumber?: number;
    opportunityNumber?: number;
    projectNumber?: number;
    projectPhaseNumber?: number;
    approvedByRepNumber?: number;
    changeOrderNumber?: number;
    invoiceNumber?: number;
    priceLevel?: number;
    leaseMonths?: number;
    payMethodId?: number;
    voidedBy?: number;
    internalExternalChangeOrder?: number;
    description: string;
    alternateContactPhoneNumber?: string;
    comment?: string;
    job?: string;
    type?: string;
    terms?: string;
    source?: string;
    status?: string;
    signedBy?: string;
    shippingInstruction?: string;
    packingInstruction?: string;
    shipper?: string;
    shippingMethod?: string;
    internalComment?: string;
    totalLineComment?: string;
    stagingLocation?: string;
    customerPurchaseOrder?: string;
    salesTaxCode: string;
    paymentMethod?: string;
    billingComment?: string;
    trackingNumber?: string;
    leaseBuyOut?: string;
    progressiveInvoiceTotalComment?: string;
    aRCustomerNumber?: string;
    stagingBin?: string;
    rateCardName?: string;
    maintenanceType?: string;
    maintenanceAmount?: string;
    quoteDate?: Date;
    expirationDate?: Date;
    statusDate?: Date;
    signedDate?: Date;
    shipDate?: Date;
    lastEditDate?: Date;
    approvedDate?: Date;
    invoiceDate?: Date;
    closeDate?: Date;
    estimatedCloseDate?: Date;
    serviceOrderDate?: Date;
    postedDate?: Date;
    paidInFullDate?: Date;
    installDate?: Date;
    dateToInstall?: Date;
    nextDate?: Date;
    shipTo?: TsiWebAlternateAddress;
    billTo?: TsiWebAlternateAddress;
    workOrderNumber?: number;
    workOrderClosed?: boolean;
    workOrderDate?: Date;
    workOrderStatus?: string;
    showInForecasts?: boolean;
    displayOnPortal?: boolean;
    approved?: boolean;
    approvedForInvoicing?: boolean;
    printLeaseInfo?: boolean;
    completelyServiceOrdered?: boolean;
    canDiscountedItemsGetQuoteDiscount?: boolean;
    paymentFromGreatAmerica?: boolean;
    changesMadeAfterPaymentFromGreatAmerica?: boolean;
    isChangeOrder?: boolean;
    freightTaxable?: boolean;
    taxLabor?: boolean;
    gSTExempt?: boolean;
    taxable?: boolean;
    taxComputedBeforeTradeIn?: boolean;
    gSTaxComputedBeforeTradeIn?: boolean;
    gSTIsTaxable?: boolean;
    discountAmount?: number;
    discountSellForPrice?: number;
    freight?: number;
    tradeIn?: number;
    credit?: number;
    deposit?: number;
    leaseDown?: number;
    leasePayment?: number;
    cashOnDelivery?: number;
    manufacturerListPrice?: number;
    bookPrice?: number;
    netSell?: number;
    grossSell?: number;
    dollarsDiscounted?: number;
    netInvoice?: number;
    laborNet?: number;
    materialNet?: number;
    taxableAmount?: number;
    tax?: number;
    gSTaxableAmount?: number;
    gSTax?: number;
    amountDue?: number;
    cost?: number;
    materialCost?: number;
    laborCost?: number;
    profit?: number;
    providerTaxableAmount?: number;
    providerTax?: number;
    percentDiscounted?: number;
    margin?: number;
    salesTaxRate?: number;
    percentagePoints?: number;
    hoursNeeded?: number;
    hoursEntered?: number;
    discountPercent?: number;
    leaseRate?: number;
    discountMarginPercent?: number;
    providerTaxRate?: number;
    gSTaxRate?: number;
    leaseIsTaxIncluded?: boolean;
}
