/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebServiceOrder } from './tsiWebServiceOrder';
import { TsiWebServiceOrderLock } from './tsiWebServiceOrderLock';


export interface TsiWebServiceOrderSummary {
    serviceOrderNumber?: number;
    serviceOrder?: TsiWebServiceOrder;
    accountName?: string;
    phoneNumber?: string;
    faxNumber?: string;
    contactName?: string;
    contactEmailAddress?: string;
    contactPhoneNumber?: string;
    primaryTechnicianName?: string;
    primaryTechnicianEmailAddress?: string;
    primaryTechnicianPhoneNumber?: string;
    takenByName?: string;
    priceLevelDescription?: string;
    payMethodName?: string;
    projectDescription?: string;
    projectPhase?: string;
    repToCreditName?: string;
    voidedByName?: string;
    contractDescription?: string;
    contractExpiration?: Date;
    externalProductName?: string;
    severityDescription?: string;
    totalExpenses?: number;
    serviceOrderProfiles?: number;
    serviceOrderSymptoms?: number;
    serviceOrderResolution?: number;
    partsUsed?: number;
    itemsServiced?: number;
    timeLogs?: number;
    openTasks?: number;
    notes?: number;
    subContractors?: number;
    quotes?: number;
    changeOrders?: number;
    hasParentServiceOrders?: boolean;
    hasChildServiceOrders?: boolean;
    hasBeenSigned?: boolean;
    hasRecurringOrder?: boolean;
    serviceOrderLock?: TsiWebServiceOrderLock;
    hasProjectBeenInvoiced?: boolean;
}
