/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebAgreement } from './tsiWebAgreement';


export interface TsiWebAgreementSummary {
    /**
     * Gets or sets the AgreementNumber
     */
    AgreementNumber?: number;
    /**
     * Gets or sets the  AccountName
     */
    AccountName?: string;
    /**
     * Gets or sets the Account Primary phone
     */
    PrimaryPhone?: string;
    /**
     * Gets or sets the  Account Primary fax
     */
    PrimaryFax?: string;
    /**
     * Gets or sets the Agreement
     */
    Agreement?: TsiWebAgreement;
    /**
     * Gets or sets the count of Additional charges
     */
    AdditionalCharges?: number;
    /**
     * Gets or sets the count CoveredAssetTypes
     */
    CoveredAssetTypes?: number;
    /**
     * Gets or sets the count CustomerAssetTypes
     */
    CustomerAssetTypes?: number;
    /**
     * Gets or sets the InternalComments
     */
    InternalComments?: string;
    /**
     * Gets or sets the count Invoices
     */
    Invoices?: number;
}
