/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebTaskAttendee } from './tsiWebTaskAttendee';


export interface TsiWebCreateTaskModel {
    ScheduleConflictedTask?: boolean;
    ScheduleThroughEndDate?: boolean;
    NumberOfTasksToSchedule?: number;
    TaskAttendees?: Array<TsiWebTaskAttendee>;
    Comment?: string;
    AccountNumber?: number;
    ContactNumber?: number;
    ScheduledForRepNumber?: number;
    ScheduledByRepNumber?: number;
    ServiceOrderNumber?: number;
    QuoteNumber?: number;
    OpportunityNumber?: number;
    ProjectNumber?: number;
    ProjectPhaseNumber?: number;
    ProjectSubPhaseAssignmentNumber?: number;
    StartDate?: Date;
    StartTime?: Date;
    EndDate?: Date;
    EndTime?: Date;
    Action?: string;
    Type?: string;
    PriorityNumber?: number;
    Priority?: string;
    HasAlarm?: boolean;
    AlarmDateTime?: Date;
    AlarmReminderQuantity?: number;
    AlarmReminderInterval?: string;
    IsCompleted?: boolean;
    IsPrivate?: boolean;
    LastModified?: Date;
    ResourceName?: string;
    IsGlobalTask?: boolean;
    IsAppointment?: boolean;
    Subject?: string;
    Location?: string;
    DueDate?: Date;
    DueTime?: Date;
}
