/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebTaskLibrary {
    TaskLibraryKeyNumber?: number;
    Subject?: string;
    Location?: string;
    TaskType?: string;
    TaskAction?: string;
    PriorityNumber?: number;
    PriorityText?: string;
    TaskComment?: string;
    ResourceName?: string;
    Duration?: number;
    DurationInterval?: string;
}
