/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebAccountAssetAssemblyDetail {
    accountAssetAssemblyDetailNumber?: number;
    itemID?: string;
    itemDescription?: string;
    serialNumber?: string;
    quantity?: number;
    purchasedFromUs?: boolean;
    datePurchased?: Date;
    purchasePrice?: number;
    warrantyExpiration?: Date;
    manufacturerWarrantyExpiration?: Date;
    vendorInvoiceNumber?: string;
    status?: string;
    statusComment?: string;
    statusDate?: Date;
    transferTo?: number;
    transferDate?: Date;
    creditMemoQuantity?: number;
    allowExchange?: boolean;
    itemExchangedFor?: number;
    exchangeNumber?: number;
    invoiceNumber?: number;
    invoiceDetailNumber?: number;
    invoiceAssemblyDetailNumber?: number;
    creditMemoNumber?: number;
    creditMemoDetailNumber?: number;
    creditMemoAssemblyDetailNumber?: number;
    manufacturerPartNumber?: string;
    vendorAccountNumber?: number;
    purchasedFromVendorDate?: Date;
    nextActionDate?: Date;
    nextActionType?: string;
    nextActionTriggersWorkflow?: boolean;
    replacedByItemId?: string;
    warrantyExpirationTriggersWorkflow?: boolean;
    printOnCustomerFacingReports?: boolean;
}
