/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SystemNullableTsiWebOptionalDateTime } from './systemNullableTsiWebOptionalDateTime';


export interface TsiWebUpdateServiceOrderItemServicedModel {
    quantity?: number;
    meterReading?: number;
    clicksUsed?: number;
    itemID?: string;
    itemDescription?: string;
    location?: string;
    problem?: string;
    repair?: string;
    serialNumber?: string;
    warrantyCovered?: boolean;
    updateContractMetersType?: string;
    completeDate?: SystemNullableTsiWebOptionalDateTime;
    lastPreventativeMaintenanceDate?: SystemNullableTsiWebOptionalDateTime;
    nextPreventativeMaintenanceDate?: SystemNullableTsiWebOptionalDateTime;
    symptom1?: string;
    symptom2?: string;
    symptom3?: string;
    symptom4?: string;
    symptom5?: string;
    resolution1?: string;
    resolution2?: string;
    resolution3?: string;
    resolution4?: string;
    resolution5?: string;
    addItemToCustomerAssets?: boolean;
    includeAssemblyDetailsWhenAddedToCustomerAssets?: boolean;
    allowDecreasedMeterReadings?: boolean;
}
