/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebServiceOrderTimeLog } from './tsiWebServiceOrderTimeLog';


export interface TsiWebSearchTimeLogResponse {
    TimeLogs?: Array<TsiWebServiceOrderTimeLog>;
    PageSize?: number;
    NextRow?: number;
    TotalCount?: number;
    Success?: boolean;
    Message?: string;
}
