/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebAlternateAddress } from './tsiWebAlternateAddress';


export interface TsiWebWorkOrder {
    WorkOrderNumber?: number;
    WorkOrderClosed?: boolean;
    WorkOrderDate?: Date;
    WorkOrderStatus?: string;
    StagingLocation?: string;
    StagingBin?: string;
    QuoteNumber?: number;
    AccountNumber?: number;
    ProjectNumber?: number;
    ProjectPhaseNumber?: number;
    BillTo?: TsiWebAlternateAddress;
    BillingComment?: string;
    PayMethodId?: number;
    Terms?: string;
    PaymentMethod?: string;
    InvoiceNumber?: number;
    InvoiceDate?: Date;
    ShipTo?: TsiWebAlternateAddress;
    PackingInstruction?: string;
    Shipper?: string;
    ShippingMethod?: string;
    ShipperPhoneNumber?: string;
    TrackingNumber?: string;
    ShipDate?: Date;
    ShippingInstruction?: string;
    InternalComment?: string;
    Comment?: string;
    NumberOfPurchaseOrders?: number;
}
