/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebMeterModel {
    /**
     * Gets or sets the contract meter name
     */
    contractMeterName?: string;
    /**
     * Gets or sets the Device ID
     */
    deviceId?: string;
    /**
     * Gets or sets the CurrentMeterReading
     */
    currentMeterReading?: number;
    /**
     * Gets or sets the DateRead
     */
    dateRead?: Date;
}
