/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebQuote } from './tsiWebQuote';


export interface TsiWebQuoteSummary {
    QuoteNumber?: number;
    Quote?: TsiWebQuote;
    Details?: number;
    ServiceOrdersCreatedFromQuote?: number;
    PurchaseOrdersContainingQuoteItems?: number;
    AccountName?: string;
    PhoneNumber?: string;
    FaxNumber?: string;
    ContactName?: string;
    ContactEmailAddress?: string;
    ContactPhoneNumber?: string;
    OwnerName?: string;
    OwnerEmailAddress?: string;
    OwnerPhoneNumber?: string;
    LastEditedRepName?: string;
    ApprovedRepName?: string;
    PayMethodName?: string;
    PriceLevelDescription?: string;
    SpecialInstructions?: string;
    CreditHoldInstructions?: string;
    OpportunityName?: string;
    ProjectDescription?: string;
    ProjectPhase?: string;
    HasProjectBeenInvoiced?: boolean;
    IsLocked?: boolean;
    ChangeOrderDescription?: string;
    ChangeOrderDateCreated?: Date;
}
