/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebAlternateAddress } from './tsiWebAlternateAddress';


export interface TsiWebQuote {
    AccountNumber: number;
    ContactNumber?: number;
    RepNumber: number;
    LastEditedByRepNumber?: number;
    OpportunityNumber?: number;
    ProjectNumber?: number;
    ProjectPhaseNumber?: number;
    ApprovedByRepNumber?: number;
    ChangeOrderNumber?: number;
    InvoiceNumber?: number;
    PriceLevel?: number;
    LeaseMonths?: number;
    PayMethodId?: number;
    VoidedBy?: number;
    InternalExternalChangeOrder?: number;
    Description: string;
    AlternateContactPhoneNumber?: string;
    Comment?: string;
    Job?: string;
    Type?: string;
    Terms?: string;
    Source?: string;
    Status?: string;
    SignedBy?: string;
    ShippingInstruction?: string;
    PackingInstruction?: string;
    Shipper?: string;
    ShippingMethod?: string;
    InternalComment?: string;
    TotalLineComment?: string;
    StagingLocation?: string;
    CustomerPurchaseOrder?: string;
    SalesTaxCode: string;
    PaymentMethod?: string;
    BillingComment?: string;
    TrackingNumber?: string;
    LeaseBuyOut?: string;
    ProgressiveInvoiceTotalComment?: string;
    ARCustomerNumber?: string;
    StagingBin?: string;
    RateCardName?: string;
    MaintenanceType?: string;
    MaintenanceAmount?: string;
    QuoteDate?: Date;
    ExpirationDate?: Date;
    StatusDate?: Date;
    SignedDate?: Date;
    ShipDate?: Date;
    LastEditDate?: Date;
    ApprovedDate?: Date;
    InvoiceDate?: Date;
    CloseDate?: Date;
    EstimatedCloseDate?: Date;
    ServiceOrderDate?: Date;
    PostedDate?: Date;
    PaidInFullDate?: Date;
    InstallDate?: Date;
    DateToInstall?: Date;
    NextDate?: Date;
    ShipTo?: TsiWebAlternateAddress;
    BillTo?: TsiWebAlternateAddress;
    WorkOrderNumber?: number;
    WorkOrderClosed?: boolean;
    WorkOrderDate?: Date;
    WorkOrderStatus?: string;
    ShowInForecasts?: boolean;
    DisplayOnPortal?: boolean;
    Approved?: boolean;
    ApprovedForInvoicing?: boolean;
    PrintLeaseInfo?: boolean;
    CompletelyServiceOrdered?: boolean;
    CanDiscountedItemsGetQuoteDiscount?: boolean;
    PaymentFromGreatAmerica?: boolean;
    ChangesMadeAfterPaymentFromGreatAmerica?: boolean;
    IsChangeOrder?: boolean;
    FreightTaxable?: boolean;
    TaxLabor?: boolean;
    GSTExempt?: boolean;
    Taxable?: boolean;
    TaxComputedBeforeTradeIn?: boolean;
    GSTaxComputedBeforeTradeIn?: boolean;
    GSTIsTaxable?: boolean;
    DiscountAmount?: number;
    DiscountSellForPrice?: number;
    Freight?: number;
    TradeIn?: number;
    Credit?: number;
    Deposit?: number;
    LeaseDown?: number;
    LeasePayment?: number;
    CashOnDelivery?: number;
    ManufacturerListPrice?: number;
    BookPrice?: number;
    NetSell?: number;
    GrossSell?: number;
    DollarsDiscounted?: number;
    NetInvoice?: number;
    LaborNet?: number;
    MaterialNet?: number;
    TaxableAmount?: number;
    Tax?: number;
    GSTaxableAmount?: number;
    GSTax?: number;
    AmountDue?: number;
    Cost?: number;
    MaterialCost?: number;
    LaborCost?: number;
    Profit?: number;
    ProviderTaxableAmount?: number;
    ProviderTax?: number;
    PercentDiscounted?: number;
    Margin?: number;
    SalesTaxRate?: number;
    PercentagePoints?: number;
    HoursNeeded?: number;
    HoursEntered?: number;
    DiscountPercent?: number;
    LeaseRate?: number;
    DiscountMarginPercent?: number;
    ProviderTaxRate?: number;
    GSTaxRate?: number;
    LeaseIsTaxIncluded?: boolean;
}
