/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebTimeSlip {
    TimeSlipNumber?: number;
    TechAssigned?: number;
    TechAssignedName?: string;
    LogReason?: string;
    LogComment?: string;
    LogHours?: number;
    LogMinutes?: number;
    ElapsedHours?: number;
    ElapsedMinutes?: number;
    Billable?: boolean;
    Mileage?: number;
    Fuel?: number;
    Parking?: number;
    Tolls?: number;
    Meals?: number;
    Accomodation?: number;
    MiscExpenses?: number;
    StartDateTime?: Date;
    EndDateTime?: Date;
    LogReasonLaborRate?: number;
    RateType?: number;
    RateBasis?: number;
    TotalExpenses?: number;
    AcceptanceStatus?: string;
    RejectedStatusReason?: string;
    InternalComments?: string;
    AcceptedOrRejectedBy?: number;
    AcceptedOrRejectedByName?: string;
    CreditUtilizationTime?: boolean;
    DeductHours?: number;
    DeductMinutes?: number;
    UtilizationHours?: number;
    UtilizationMinutes?: number;
    DateCreated?: Date;
}
