/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebOpportunityStageLog {
    opportunityStageLogId?: number;
    nextStep?: string;
    stageChangedTo?: string;
    stageChangedByRep?: number;
    expectedAmount?: number;
    probablilityPercent?: number;
    stageChangedDate?: Date;
    dateLeftThisStage?: Date;
}
