/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebTimeEntry {
    entryType?: string;
    timeEntryKeyNumber?: number;
    serviceOrderNumber?: number;
    sOBriefDescription?: string;
    sOWorkPerformed?: string;
    logReason?: string;
    techAssigned?: number;
    techAssignedName?: string;
    startDateTime?: Date;
    endDateTime?: Date;
    logHours?: number;
    logMinutes?: number;
    elapsedHours?: number;
    elapsedMinutes?: number;
    utilizationHours?: number;
    utilizationMinutes?: number;
    accountNumber?: number;
    accountName?: string;
    acceptanceStatus?: number;
    internalComments?: string;
    logComment?: string;
    billable?: boolean;
    chargable?: boolean;
    billingOption?: string;
    unitFactor?: number;
    totalUnits?: number;
    contractNumber?: number;
}
