/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebItemCovered {
    /**
     * Gets or sets the ContractDetailKeyNumber
     */
    contractDetailKeyNumber?: number;
    /**
     * Gets or sets the AccountNumber
     */
    accountNumber?: number;
    /**
     * Gets or sets the serial number
     */
    serialNumber?: string;
    /**
     * Gets or sets the Item ID
     */
    itemID?: string;
    /**
     * Gets or sets the ItemDescription
     */
    itemDescription?: string;
    /**
     * Gets or sets the Quantity
     */
    quantity?: number;
    /**
     * Gets or sets the refernce
     */
    reference?: string;
    /**
     * Gets or sets the warranty expiration
     */
    warrantyExpiration?: Date;
    /**
     * Gets or sets the Cancel Date
     */
    cancelDate?: Date;
    /**
     * Gets or sets the contact name
     */
    contactName?: string;
    /**
     * Gets or sets the contact phone
     */
    contactPhoneNumber?: string;
    /**
     * Gets or sets the start date
     */
    startDate?: Date;
    /**
     * Gets or sets the YearlyPrice
     */
    yearlyPrice?: number;
    /**
     * Gets or sets the RenewalListPercentage
     */
    renewalListPercentage?: number;
    /**
     * Gets or sets the ListPrice
     */
    renewalListPrice?: number;
    /**
     * Gets or sets the CustomeInventoryNumber
     */
    customerInventoryNumber?: number;
    /**
     * Gets or sets the  ContractPrice
     */
    contractPrice?: number;
    /**
     * Gets or sets the  DeviceId
     */
    deviceId?: string;
    /**
     * Gets or sets the  SO Priority
     */
    serviceOrderPriority?: string;
}
