/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebAlternateAddress } from './tsiWebAlternateAddress';


export interface TsiWebPurchaseOrder {
    Description?: string;
    Reference?: string;
    PurchaseOrderDate?: Date;
    ConfirmedBy?: string;
    ConfirmedDate?: Date;
    HasBeenPrinted?: boolean;
    Status?: string;
    StatusDate?: Date;
    BuyingRepNumber?: number;
    BuyingRepName?: string;
    Comments?: string;
    OrderTerms?: string;
    FreightTerms?: string;
    ShippingMethod?: string;
    UpdateLatestCost?: boolean;
    AllowBackOrders?: boolean;
    LineItems?: number;
    ProjectedTotalInventory?: number;
    ProjectedCost?: number;
    ExpectedDate?: Date;
    DefaultReceivingLocation?: string;
    DefaultCostLevel?: string;
    OrderIdentificationNumber?: string;
    InvoiceTerms?: string;
    Freight?: number;
    BlindShip?: boolean;
    TrackingNumber?: string;
    RequestedRepNumber?: number;
    RequestedRepName?: string;
    LinkedAccountNumber?: number;
    LinkedQuoteNumber?: number;
    LinkedServiceOrderNumber?: number;
    PaidInFull?: boolean;
    InternalComments?: string;
    VendorAccountNumber?: number;
    PurchaseOrderWasAddedToBatch?: boolean;
    ProjectNumber?: number;
    Shipper?: string;
    DefaultReceivingBin?: string;
    ShipTo?: TsiWebAlternateAddress;
    BillTo?: TsiWebAlternateAddress;
}
