/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebPurchaseOrder } from './tsiWebPurchaseOrder';
import { TsiWebPurchaseOrderLineItem } from './tsiWebPurchaseOrderLineItem';
import { TsiWebPurchaseOrderRelatedDocument } from './tsiWebPurchaseOrderRelatedDocument';
import { TsiWebVendor } from './tsiWebVendor';


export interface TsiWebPurchaseOrderDetail {
    PurchaseOrderNumber?: number;
    PurchaseOrder?: TsiWebPurchaseOrder;
    PurchaseOrderVendorSummary?: TsiWebVendor;
    PurchaseOrderLineItems?: Array<TsiWebPurchaseOrderLineItem>;
    PurchaseOrderRelatedDocuments?: Array<TsiWebPurchaseOrderRelatedDocument>;
}
