/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebPartAndLabor {
    /**
     * Gets or sets the AccountNumber
     */
    AccountNumber?: number;
    /**
     * Gets or sets the SOPartsUsedKeyID
     */
    SOPartsUsedNumber?: number;
    /**
     * Gets or sets the SONumber
     */
    ServiceOrderNumber?: number;
    /**
     * Gets or sets the ItemID
     */
    ItemID?: string;
    /**
     * Gets or sets the Description
     */
    PartsDescription?: string;
    /**
     * Gets or sets the Quantity
     */
    Quantity?: number;
    /**
     * Gets or sets the SellingPrice
     */
    SellingPrice?: number;
    /**
     * Gets or sets the TotalSellingPrice
     */
    TotalSellingPrice?: number;
    /**
     * Gets or sets the QuantityOrdered
     */
    QuantityOrdered?: number;
    /**
     * Gets or sets the QuantityReceived
     */
    QuantityReceived?: number;
    /**
     * Gets or sets the QuantityFilled
     */
    QuantityFilled?: number;
    /**
     * Gets or sets the QuantityInvoiced
     */
    QuantityInvoiced?: number;
    /**
     * Gets or sets the QuantityPosted
     */
    QuantityPosted?: number;
    /**
     * Gets or sets the QuantityShipped
     */
    QuantityShipped?: number;
    /**
     * Gets or sets the Exchange
     */
    Exchange?: boolean;
    /**
     * Gets or sets the UnderContract
     */
    UnderContract?: boolean;
    /**
     * Gets or sets the Taxed
     */
    Taxed?: boolean;
    /**
     * Gets or sets the ProviderTaxed
     */
    ProviderTaxed?: boolean;
    /**
     * Gets or sets the CostGLCode
     */
    CostGLCode?: string;
    /**
     * Gets or sets the IncomeGLCode
     */
    IncomeGLCode?: string;
    /**
     * Gets or sets the Notes
     */
    Notes?: string;
    /**
     * Gets or sets the Item Type
     */
    ItemType?: string;
    /**
     * Gets or sets the Item Assembly type, if the Item is of type assembly
     */
    AssemblyType?: string;
    /**
     * Gets or sets the Cost
     */
    Cost?: number;
    /**
     * Gets or sets the PrintOnInvoice
     */
    PrintOnInvoice?: boolean;
    /**
     * Gets or sets the PartNumber
     */
    PartNumber?: string;
    /**
     * Gets or sets the Order By Date
     */
    OrderByDate?: Date;
    /**
     * Gets or sets the Is RepairLevel
     */
    IsRepairLevel?: boolean;
    /**
     * Gets or sets the Item Serviced
     */
    ItemServiced?: string;
    /**
     * Gets or sets the Project Phase
     */
    ProjectPhase?: string;
    /**
     * Gets or sets the Install Location
     */
    InstallLocation?: string;
    /**
     * Gets or sets the PriceLevel
     */
    PriceLevel?: number;
}
