/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebAccountingDetail {
    ARCustomerNumber?: string;
    SalesTaxCode: string;
    CreditHoldSpecialInstructions?: string;
    AccountingCompanyId?: string;
    BOTaxCode?: string;
    BOTaxType?: string;
    DefaultPaymentType?: string;
    DefaultShipMethod?: string;
    GSTTaxExemptId?: string;
    TaxExemptCategory?: string;
    TaxExemptId?: string;
    DefaultTerms?: string;
    Department?: string;
    DefaultPriceLevel?: string;
    PrimaryBillToName?: string;
    PrimaryShipToName?: string;
    DefaultPayMethodName?: string;
    DefaultLaborRate?: number;
    AllowedInvoicePaymentLateDays?: number;
    DefaultPayMethodId?: number;
    DefaultPriceLevelId?: number;
    PrimaryBillToId?: number;
    PrimaryShipToId?: number;
    AddToAccountsReceiveable?: boolean;
    AlwaysBillParent?: boolean;
    ApplyQuantityDiscounts?: boolean;
    CreditHold?: boolean;
    EnableCentralBilling?: boolean;
    GSTExempt?: boolean;
    ProviderTaxExempt?: boolean;
    TaxFreight?: boolean;
    TaxLabor?: boolean;
    IncludeParentOrdersInCBIInvoices?: boolean;
}
