/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebAccountAsset {
    ItemID?: string;
    ItemDescription?: string;
    SerialNumber?: string;
    Status?: string;
    StatusComment?: string;
    Quantity?: number;
    VendorInvoiceNumber?: string;
    PurchasedFromUs?: boolean;
    DatePurchased?: Date;
    PurchasePrice?: number;
    WarrantyExpiration?: Date;
    LastPMDate?: Date;
    CurrMeterReading?: number;
    OrigMeterReading?: number;
    NextPMDate?: Date;
    ServicePriority?: number;
    ContractNumber?: number;
    ContractDetailNumber?: number;
    Location?: string;
    ContactName?: string;
    ContactNumber?: number;
    ContactPhone?: string;
    YearlyMaintPrice?: number;
    DatePurchasedFromVendor?: Date;
    ManufacturerWarrantyExpiration?: Date;
    Reference?: string;
    StatusDate?: Date;
    TransferTo?: number;
    TransferDate?: Date;
    AllowExchange?: boolean;
    ExchangeNumber?: number;
    ItemExchangedFor?: number;
    AssemblyFlag?: boolean;
    Comments?: string;
    CreditMemoNumber?: number;
    CreditMemoDetailNumber?: number;
    CreditMemoAssemblyDetailNumber?: number;
    CreditMemoQuantity?: number;
    InvoiceNumber?: number;
    InvoiceDetailNumber?: number;
    InvoiceAssemblyDetailNumber?: number;
    ManufacturerPartNumber?: string;
    VendorAccountNumber?: number;
    BMFLastProcessed?: Date;
    IpAddress?: string;
    NextActionDate?: Date;
    NextActionType?: string;
    NextActionTriggersWorkflow?: boolean;
    ReplacedByItemId?: string;
    WarrantyExpirationTriggersWorkflow?: boolean;
    PrimaryRepNumber?: number;
    PrintOnCustomerFacingReports?: boolean;
    DeviceId?: string;
}
