/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebServiceOrderSubContractor {
    AssignedSubContractorID?: number;
    ServiceOrderNumber?: number;
    AccountNumber?: number;
    AccountName?: string;
    Responsibility?: string;
    ProjectedStartDate?: Date;
    ActualStartDate?: Date;
    ProjectedCompletionDate?: Date;
    ActualCompleteDate?: Date;
    BidPrice?: number;
    ActualPrice?: number;
    WorkRequested?: string;
    WorkAgreementInPlace?: boolean;
    SubContractorGetsPermits?: boolean;
    FieldReportsCurrent?: boolean;
}
