/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebServiceOrderTimeLog {
    TimeLogNumber?: number;
    Tech?: number;
    ContractNumber?: number;
    LogHours?: number;
    LogMinutes?: number;
    ElapsedHours?: number;
    ElapsedMinutes?: number;
    UsageInvoiceNumber?: number;
    RateType?: string;
    RateBasis?: string;
    CopyCommentsIndicator?: number;
    ReviewedBy?: number;
    DeductHours?: number;
    UtilizationHours?: number;
    InternalComments?: string;
    RejectedStatusReason?: string;
    Comment?: string;
    Reason?: string;
    ReviewedByName?: string;
    TechName?: string;
    Chargable?: boolean;
    Billable?: boolean;
    ApplyMinimum?: boolean;
    CreditUtilizationTime?: boolean;
    BillForUtilizedTime?: boolean;
    AcceptanceStatus?: string;
    StartDateTime?: Date;
    EndDateTime?: Date;
    DateCreated?: Date;
    TotalUnits?: number;
    TimeConvertedToLaborItem?: number;
    LogReasonLaborRate?: number;
    LaborRate?: number;
    UnitFactor?: number;
    DeductMinutes?: number;
    UtilizationMinutes?: number;
    TimeToInvoice?: number;
}
