/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebAccount } from './tsiWebAccount';
import { TsiWebAssignedMarketingGroup } from './tsiWebAssignedMarketingGroup';
import { TsiWebAssignedMarketingProfile } from './tsiWebAssignedMarketingProfile';
import { TsiWebContact } from './tsiWebContact';
import { TsiWebCustomField } from './tsiWebCustomField';
import { TsiWebEmailAddress } from './tsiWebEmailAddress';
import { TsiWebPhoneNumber } from './tsiWebPhoneNumber';


export interface TsiWebContactDetail {
    contactNumber?: number;
    contact?: TsiWebContact;
    phoneNumbers?: Array<TsiWebPhoneNumber>;
    emailAddresses?: Array<TsiWebEmailAddress>;
    groups?: Array<TsiWebAssignedMarketingGroup>;
    profiles?: Array<TsiWebAssignedMarketingProfile>;
    account?: TsiWebAccount;
    customFields?: Array<TsiWebCustomField>;
    isPrimaryContact?: boolean;
    journalEntries?: number;
    openOpportunities?: number;
    openServiceOrders?: number;
    pastDueTasks?: number;
}
