/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TsiWebAccountingDetail {
    aRCustomerNumber?: string;
    salesTaxCode: string;
    creditHoldSpecialInstructions?: string;
    accountingCompanyId?: string;
    bOTaxCode?: string;
    bOTaxType?: string;
    defaultPaymentType?: string;
    defaultShipMethod?: string;
    gSTTaxExemptId?: string;
    taxExemptCategory?: string;
    taxExemptId?: string;
    defaultTerms?: string;
    department?: string;
    defaultPriceLevel?: string;
    primaryBillToName?: string;
    primaryShipToName?: string;
    defaultPayMethodName?: string;
    defaultLaborRate?: number;
    allowedInvoicePaymentLateDays?: number;
    defaultPayMethodId?: number;
    defaultPriceLevelId?: number;
    primaryBillToId?: number;
    primaryShipToId?: number;
    addToAccountsReceiveable?: boolean;
    alwaysBillParent?: boolean;
    applyQuantityDiscounts?: boolean;
    creditHold?: boolean;
    enableCentralBilling?: boolean;
    gSTExempt?: boolean;
    providerTaxExempt?: boolean;
    taxFreight?: boolean;
    taxLabor?: boolean;
    includeParentOrdersInCBIInvoices?: boolean;
}
