/**
 * Tigerpaw API Method Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TsiWebContract } from './tsiWebContract';
import { TsiWebContractAccount } from './tsiWebContractAccount';


export interface TsiWebContractSummary {
    /**
     * Gets or sets the ContractNumber
     */
    ContractNumber?: number;
    /**
     * Gets or sets the Contract
     */
    Contract?: TsiWebContract;
    /**
     * Gets or sets the created by rep name
     */
    CreatedByRepName?: string;
    /**
     * Gets or sets the created by rep email address
     */
    CreatedByRepEmailAddress?: string;
    /**
     * Gets or sets the created by rep phone number
     */
    CreatedByRepPhoneNumber?: string;
    /**
     * Gets or sets the assigned tech rep name
     */
    AssignedTechRepName?: string;
    /**
     * Gets or sets the assigned tech rep email adress
     */
    AssignedTechRepEmailAddress?: string;
    /**
     * Gets or sets the assigned tech rep phone number
     */
    AssignedTechRepPhoneNumber?: string;
    /**
     * Gets or sets the rep to credit rep name
     */
    RepToCreditName?: string;
    /**
     * Gets or sets the rep to credit rep email address
     */
    RepToCreditEmailAddress?: string;
    /**
     * Gets or sets the rep to credit rep phone number
     */
    RepToCreditPhoneNumber?: string;
    /**
     * Gets or sets the ContractAccount
     */
    ContractAccount?: Array<TsiWebContractAccount>;
    /**
     * Gets or sets the ItemsCovered
     */
    ItemsCovered?: number;
}
