export * from './accounts.service';
import { AccountsService } from './accounts.service';
export * from './agreements.service';
import { AgreementsService } from './agreements.service';
export * from './contacts.service';
import { ContactsService } from './contacts.service';
export * from './contracts.service';
import { ContractsService } from './contracts.service';
export * from './diagnostics.service';
import { DiagnosticsService } from './diagnostics.service';
export * from './masterTables.service';
import { MasterTablesService } from './masterTables.service';
export * from './opportunity.service';
import { OpportunityService } from './opportunity.service';
export * from './priceBook.service';
import { PriceBookService } from './priceBook.service';
export * from './projects.service';
import { ProjectsService } from './projects.service';
export * from './purchaseOrders.service';
import { PurchaseOrdersService } from './purchaseOrders.service';
export * from './quotes.service';
import { QuotesService } from './quotes.service';
export * from './reps.service';
import { RepsService } from './reps.service';
export * from './serviceOrders.service';
import { ServiceOrdersService } from './serviceOrders.service';
export * from './tasks.service';
import { TasksService } from './tasks.service';
export * from './timeEntry.service';
import { TimeEntryService } from './timeEntry.service';
export * from './timeSlip.service';
import { TimeSlipService } from './timeSlip.service';
export const APIS = [AccountsService, AgreementsService, ContactsService, ContractsService, DiagnosticsService, MasterTablesService, OpportunityService, PriceBookService, ProjectsService, PurchaseOrdersService, QuotesService, RepsService, ServiceOrdersService, TasksService, TimeEntryService, TimeSlipService];
